apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-access-binding
  namespace: demo-app
subjects:
- kind: User
  name: system:node:ubuntu-s-1vcpu-1gb-nyc1-01
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pvc-access
  apiGroup: rbac.authorization.k8s.io
