apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:  
  name: pvc-access
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete", "update"]
