apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-pvc
spec:
  storageClassName: fast-storage  # Use the new storage class here
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
